name: r_phylogenetics_worshop-binderized
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r-base>=4.1
  - r-irkernel
  - r-tidyverse
  - bioconductor-ggtree
  - bioconductor-treeio
  - r-phytools
  - r-ape
  - r-ggpubr
  - r-ggnewscale
  - r-ggstance